rent/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html', authentication_form=forms.CustomAuthForm), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'dashboard/$', views.user_dashboard, name='dashboard'),
]

rent/posts/urls.py
from django.conf.urls import url
from . import views


app_name = 'posts'

urlpatterns = [
    # url(r'^new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^new/$', views.create_post, name='post_new'),
    url(r'^get_location/$', views.get_location_data, name='get_location'),
    url(r'^(?P<pk>\d+)', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^remove/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^getcontact/(?P<pk>\d+)/$', views.get_user_contact, name='getcontact')
]

rent/rent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^receivepay', views.process_user_sms, name='user_sms'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_no = models.CharField(max_length=13)
    address = models.CharField(max_length=100)
    masked_id = models.CharField(max_length=200, null=True)
    is_subscribed = models.BooleanField(default=False)

    # use the ratings relation here, and add a generic field
    # like {% ratings user.userprofile %}

    def __str__(self):
        return self.user.username

rent/accounts/forms.py
from accounts.models import UserProfile
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput


class CreateUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    phone_no = forms.CharField(required=True, max_length=13, widget=forms.TextInput(attrs={'placeholder': 'Phone No'}))
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Address'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))

    class Meta():
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email'
        )


# this is created only to add the extra placeholders :(
class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(
        attrs={'class': 'validate', 'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(
        attrs={'placeholder': 'Password'}))

rent/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView, ListView
from django.contrib import messages
from accounts.models import UserProfile
from posts.models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.


class SignUp(CreateView):
    form_class = forms.CreateUserForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        c = {'form': form}
        user = form.save(commit=False)

        # cleaned data
        phone_number = form.cleaned_data['phone_no']
        address = form.cleaned_data['address']
        password = form.cleaned_data['password']
        password2 = form.cleaned_data['password2']

        # confirm password
        if password and password2 and password != password2:
            messages.error(self.request, "Passwords do not Match",
                           extra_tags='alert alert-danger')
            return render(self.request, self.template_name, c)
        user.set_password(password)
        user.save()

        # create user-profile model with extra info
        UserProfile.objects.create(
            user=user, phone_no=phone_number, address=address)

        return super().form_valid(form)


# handles the user dashboard
@login_required
def user_dashboard(request):
    objects = Post.objects.filter(
        author=request.user).order_by('-creation_date')
    return render(request, 'accounts/dashboard.html', {'post_list': objects})

rent/accounts/templates/accounts/dashboard.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load ratings %}
{% block extra_js %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% endblock extra_js %}
{% block content %}
    <div class="container">
        <h1>Hello {{ user.username }}</h1>
        <hr>
        <h3>Your Rating</h3>
        {% ratings user %}
        <hr>
        {% if not user.userprofile.is_subscribed %}
            <div class="alert alert-danger">
                You are not subscribed yet. To subscribe, go to message option in your phone and 
                type "homeview {{user.username}}" and send it to 21213
            </div>
        {% else %}
            <div class="alert alert-success">
                You are successfully subscribed
            </div>
        {% endif %}
        <h1>Posts by you:</h1>
        {% for post in post_list %}
            <a href="{% url 'posts:post_detail' pk=post.pk %}">{{ post.district }}-{{ post.area }}-{{ post.creation_date }}</a>
            <br>
        {% endfor %}
    </div>
{% endblock content %}

rent/accounts/templates/accounts/login.html
<!DOCTYPE html> 
{% extends "base.html" %} 
{% load bootstrap4 %} 
{% load staticfiles %}
{% block extra_js %}
    <link rel="stylesheet" href="{% static 'css/login-form.css' %}">
{% endblock extra_js %}
{% block content %}
<div class="container">
    <!-- <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %} {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Login">
    </form> -->
    <div class="row justify-content-md-center">
        <div class="col col-lg-6">
            <div class="login-page">
                <div class="form">
                    <form class="login-form" method="POST">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            {% for err in form.non_field_errors  %}
                                <div class="alert alert-danger">{{err}}</div>
                            {% endfor %}
                        {% endif %}
                        {{ form.username.errors }}
                        {{ form.username }}
                        {{ form.password.errors }}
                        {{ form.password }}
                        <button type="submit">login</button>
                        <p class="message">Not registered?
                            <a href="{% url 'accounts:signup' %}">Create an account</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

rent/accounts/templates/accounts/signup.html
<!DOCTYPE html> 
{% extends "base.html" %} 
{% load staticfiles %}
{% load bootstrap4 %} 
{% block extra_js %}
    <link rel="stylesheet" href="{% static 'css/login-form.css' %}">
{% endblock extra_js %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col col-lg-6">
                <div class="login-page">
                        <div class="form">
                            <form class="login-form" method="POST">
                                {% csrf_token %}
                                {% if form.non_field_errors %}
                                    {% for err in form.non_field_errors  %}
                                        <div class="alert alert-danger">{{err}}</div>
                                    {% endfor %}
                                {% endif %}
                                {% for message  in messages %}
                                    <div class="alert alert-danger">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                                {{ form.username }}
                                {{ form.first_name }}
                                {{ form.last_name }}
                                {{ form.email }}
                                {{ form.password }}
                                {{ form.password2 }}
                                {{ form.phone_no }}
                                {{ form.address }}
                                <div class="alert alert-primary">
                                    After registering, you have to subscribe to the service using the given phone no
                                </div>
                                <button type="submit">register</button>
                                <p class="message">Already registered?
                                    <a href="{% url 'accounts:login' %}">Sign In</a>
                                </p>
                            </form>
                        </div>
                    </div>
        </div>
    </div>
    
</div>
{% endblock content %}