rent/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html', authentication_form=forms.CustomAuthForm), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'dashboard/$', views.user_dashboard, name='dashboard'),
]

rent/posts/urls.py
from django.conf.urls import url
from . import views


app_name = 'posts'

urlpatterns = [
    # url(r'^new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^new/$', views.create_post, name='post_new'),
    url(r'^get_location/$', views.get_location_data, name='get_location'),
    url(r'^(?P<pk>\d+)', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^remove/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^getcontact/(?P<pk>\d+)/$', views.get_user_contact, name='getcontact')
]

rent/rent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^receivepay', views.process_user_sms, name='user_sms'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class District(models.Model):
    district_name = models.CharField(max_length=50)

    def __str__(self):
        return self.district_name


class Area(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    area_name = models.CharField(max_length=50)

    def __str__(self):
        return self.area_name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    house_name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    house_size = models.IntegerField()
    address = models.CharField(max_length=255)
    rent = models.IntegerField()
    description = models.TextField()
    family_allowed = models.BooleanField()
    office_allowed = models.BooleanField()
    bachelors_allowed = models.BooleanField()
    creation_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "%s - %s - %s" % (self.pk, self.author.username, self.creation_date)

def get_image_filename(instance, filename):
    name = instance.post.house_name
    slug = slugify(name)
    return 'post_images/%s-%s' % (slug, filename)

class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to=get_image_filename, verbose_name='Image')

rent/templates/base.html
<!DOCTYPE html> {% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HomeView</title>

    <!-- Custom fonts/icons for this template -->
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Exo+2|Quicksand" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/landing-page.min.css' %}" rel="stylesheet">

    <!-- Bootstrap and JQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script> 
    {% block extra_js %} 
    
    {% endblock extra_js %}
</head>

<body>
    <!-- navbar here -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">HomeView</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="#">About Us</a>
                    <a class="nav-item nav-link" href="#">Contact</a>
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="#">Welcome: {{ user.username }}</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
                    <a class="nav-item nav-link" href="{% url 'posts:post_new' %}">Create Ad</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">
                        <span class="icon-logout"></span> Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">
                        <span class="icon-login"></span> Login</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">
                        <span class="icon-user"></span> Signup</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <!-- navbar end-->

    <div class="mycontainer">
        {% block content %} {% endblock content %}
    </div>
    <footer class="footer bg-light">
        <div class="container">
          <a href="">Home</a>
          <a href="">About</a>
          <a href="">Contact</a>
        </div>
      </footer>
</body>

</html>

rent/templates/index.html
{% extends "base.html" %} 
{% load bootstrap4 %} 
{% block extra_js %}
<script>
    $(document).ready(function () {

        // clear the default data from area_choice, and later update
        // areas based on user's district choice
        $("#area_choice").html('<option value="" selected>---------</option>');

        $("#district_choice").click(function () {
            console.log("requesting new data");
            var req = $.ajax({
                url: "{% url 'posts:get_location' %}",
                type: "POST",
                data: {
                    user_choice: $("#district_choice option:selected").text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType: "html",

                success: function (data) {
                    console.log("data retrieved");
                    console.log(data);
                    $("#area_choice").html(data);
                    $("#area_choice").prepend('<option value="" selected>---------</option>');
                },

                error: function () {
                    console.log("error occured");
                }
            });
        });

    });
</script> 
{% endblock extra_js %} 

{% block content %}
    <!-- Masthead -->
    <header class="masthead text-white text-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col col-lg-7">
                    {% if user.is_authenticated %}
                    <h1>Welcome</h1>
                    <h2>Search home</h2>
                    {% if search_form %}
                    <form method="POST">
                        {% csrf_token %} {% bootstrap_form search_form %}
                        <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                    {% endif %} {% else %}
                    <h2><strong>An ultimate house-renting solution. Please login to continue</strong></h1>
                        {% endif %}
                </div>
            </div>
        </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="features-icons-item mx-auto mb-2 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                            <i class="icon-screen-desktop m-auto text-primary"></i>
                        </div>
                        <h3>Post an Ad</h3>
                        <p class="lead mb-0">Make your home available to renters</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="features-icons-item mx-auto mb-3 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                            <i class="icon-layers m-auto text-primary"></i>
                        </div>
                        <h3>Filtered Search</h3>
                        <p class="lead mb-0">Find the home you want with all criterias met</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <div class="container-fluid">
        <!-- Image Showcases -->
        <section class="showcase">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
    
                    <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('../static/img/home.jpg');"></div>
                    <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                        <h2>Looking for homes to rent ?</h2>
                        <p class="lead mb-0">Time constraint and hastle of roaming in streets looking for suitable homes pulling you down. Filter your search here
                            and find your home easily. Looking for homes for rent was never this easy! </p>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-lg-6 text-white showcase-img" style="background-image: url('../static/img/landlord.jpg');"></div>
                    <div class="col-lg-6 my-auto showcase-text">
                        <h2>LandLord?</h2>
                        <p class="lead mb-0">Get your homes rented easily. More number of views online than people physically coming to see your home each time.
                            Lesser hastle of showing your home everytime to potential tenets !</p>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('../static/img/bg-showcase-3.jpg');"></div>
                    <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                        <h2>Save your precious time</h2>
                        <p class="lead mb-0">Now, searching for home is not consuming for all. Continue to cope up with busy 
                            schedule, and still search for your dream home
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Footer -->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item">
                            <a href="About us.html">About</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="Contact.html">Contact</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="FAQ.html">FAQ</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="FeedBack.html">FeedBack</a>
                        </li>
                    </ul>

                </div>
                <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item mr-3">
                            <a href="#">
                                <i class="fa fa-facebook fa-2x fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-instagram fa-2x fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- My main-->
{% endblock content %}

rent/templates/search_results.html
{% extends "base.html" %} {% load staticfiles %} {% block content %}
<div class="container">
    <!-- <h1>Search Results</h1>
        {% if results %}
            {% for r in results %}
                <a href="{% url 'posts:post_detail' pk=r.pk %}">{{ r.author }}-{{ r.district }}-{{ r.area }}-{{ r.creation_date }}</a><br>
            {% endfor %}
        {% else %}
            <p>Sorry, no results found under selected filters. Try to broaden your criteria</p>
        {% endif %} -->
    <div class="row justify-content-md-center">
        <div class="col-sm-12 col-md-10 col-md-offset-2">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>House</th>

                        <th class="text-center">Size</th>
                        <th class="text-center">Rent</th>
                        <th> </th>
                    </tr>
                </thead>
                {% if not results %}
                    <p class="mt-5">No results found for your criteria</p>
                {% else %}
                    <p class="mt-5">Showing results under the district {{ results.0.district }} </p>
                {% endif %}
                <tbody>
                    {% for r in results %}
                    <tr>
                            <td class="col-sm-2 col-md-10">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#">
                                        <img class="media-object pr-3" src="{{ r.images_set.all.first.image.url }}" alt="No Image" style="width: 80px; height: 72px;"> </a>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            <a href="{% url 'posts:post_detail' pk=r.pk %}">{{ r.house_name }}</a>
                                        </h4>
                                        <h5 class="media-heading">{{ r.area }}</h5>
                                    </div>
                                </div>
                            </td>

                            <td class="col-sm-2 col-md-2 text-center">
                                <strong>{{ r.house_size }} sqft</strong>
                            </td>
                            <td class="col-sm-2 col-md-2 text-center">
                                <strong>{{ r.rent }}</strong>
                            </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>

{% endblock content %}