rent/posts/urls.py
from django.conf.urls import url
from . import views


app_name = 'posts'

urlpatterns = [
    # url(r'^new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^new/$', views.create_post, name='post_new'),
    url(r'^get_location/$', views.get_location_data, name='get_location'),
    url(r'^(?P<pk>\d+)', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^remove/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^getcontact/(?P<pk>\d+)/$', views.get_user_contact, name='getcontact')
]

rent/rent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^receivepay', views.process_user_sms, name='user_sms'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class District(models.Model):
    district_name = models.CharField(max_length=50)

    def __str__(self):
        return self.district_name


class Area(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    area_name = models.CharField(max_length=50)

    def __str__(self):
        return self.area_name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    house_name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    house_size = models.IntegerField()
    address = models.CharField(max_length=255)
    rent = models.IntegerField()
    description = models.TextField()
    family_allowed = models.BooleanField()
    office_allowed = models.BooleanField()
    bachelors_allowed = models.BooleanField()
    creation_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "%s - %s - %s" % (self.pk, self.author.username, self.creation_date)

def get_image_filename(instance, filename):
    name = instance.post.house_name
    slug = slugify(name)
    return 'post_images/%s-%s' % (slug, filename)

class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to=get_image_filename, verbose_name='Image')

rent/posts/forms.py
from django import forms
from posts.models import Post, District, Area, Images


class PostForm(forms.ModelForm):
    district = forms.ModelChoiceField(queryset=District.objects.all(
    ), widget=forms.Select(attrs={'id': 'district_choice'}))

    area = forms.ModelChoiceField(queryset=Area.objects.all(
    ), widget=forms.Select(attrs={'id': 'area_choice'}))

    class Meta():
        model = Post
        fields = ('house_name', 'district', 'area', 'house_size', 'address', 'description', 'rent',
                  'family_allowed', 'office_allowed', 'bachelors_allowed')


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta():
        model = Images
        fields = ('image',)

rent/posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, TemplateView, ListView, DetailView, DeleteView
from . import forms
from posts.models import Post, District, Area, Images
from django.utils import timezone
from django.forms.models import modelformset_factory
from django import forms as django_forms
import posts.api as api
from django.contrib import messages
from django.contrib.auth.models import User


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'posts/post_detail.html'
    form_class = forms.PostForm
    model = Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.creation_date = timezone.now()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class PostDetailView(DetailView):
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('home')


# handle ajax request to update locations based on district
def get_location_data(request):
    print("execute successful")
    if request.is_ajax():
        html_response = ""
        obj = Area.objects.filter(
            district__district_name=request.POST.get('user_choice'))

        for i in obj:
            html_response += '<option value="%s">%s</option>' % (
                i.pk, i.area_name)
        return HttpResponse(html_response)


@login_required
def get_user_contact(request, pk):
    post = Post.objects.get(pk=pk)
    user = get_object_or_404(User, username=request.user.username)
    req = api.Caas(user.userprofile.phone_no)
    req.direct_debit('25601', '2')
    return render(request, 'posts/getcontact.html', {'post': post})


@login_required
def create_post(request):
    ImageFormSet = modelformset_factory(Images, form=forms.ImageForm, extra=3)

    if request.method == 'POST':
        postForm = forms.PostForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if postForm.is_valid() and formset.is_valid():
            # user = get_object_or_404(User, username=request.user.username)
            # req = api.Caas('password', user.userprofile.phone_no, 'APP_000001')
            

            # if not req.direct_debit('25601', '50'):
            #     messages.error(request, 'An error occured while trying to debit from the user account')
            #     return render(request, 'posts/post_form.html', context={'form': postForm, 'formset': formset})

            post_form = postForm.save(commit=False)
            post_form.author = request.user
            post_form.creation_date = timezone.now()
            post_form.save()

            # handling images
            if len(request.FILES) > 0:
                for i in range(len(request.FILES)):
                    image = formset.cleaned_data[i]['image']
                    photo = Images(post=post_form, image=image)
                    photo.save()
            return render(request, 'posts/post_detail.html', context={'post': post_form})
        else:
            print(postForm.errors, formset.errors)

    else:
        postForm = forms.PostForm()
        formset = ImageFormSet(queryset=Images.objects.none())
        return render(request, 'posts/post_form.html', context={'form': postForm, 'formset': formset})

rent/posts/templates/posts/getcontact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container mt-5">
        <p>The contact number for the landlord is: <h1>{{post.author.userprofile.phone_no}}</h1></p>
        <button class="btn btn-success">Confirm Rent</button>
    </div>
{% endblock content %}

rent/posts/templates/posts/post_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ object }}?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock content %}

rent/posts/templates/posts/post_detail.html
<!DOCYTPE html>
{% extends "base.html" %}
{% load static %}
{% load ratings %}
{% block extra_js %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% endblock extra_js %}

{% block content %}
    <div class="container mt-5">
        <!-- Rating -->
        <div class="row justify-content-md-center">
            <div class="col col-lg-3">
                <p>Rate {{ post.author.first_name }} {{ post.author.last_name }}</p>
                {% ratings post.author %}
                <hr>
            </div>

            <div class="col col-lg-6">
                <strong>House Name</strong>
                <p>{{ post.house_name }}</p>
                <strong>Address</strong>
                <p>{{ post.address }}</p>
                <strong>Description</strong>
                <p>{{ post.description }}</p>
                <div class="image_view my-5">
                    {% for image in post.images_set.all %}
                        <img src="{{ image.image.url }}" alt="" height="200" width="180">
                    {% endfor %}    
                </div> 
                {% if post.family_allowed %}
                    <p>Family Allowed: Yes</p>
                {% endif %}
                
                {% if post.office_allowed %}
                    <p>Office Allowed: Yes</p>
                {% endif %}

                {% if post.bachelors_allowed %}
                    <p>Bachelors Allowed: Yes</p>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if user.username == post.author.username %}
                        <a class="btn btn-danger" href="{% url 'posts:post_remove' pk=post.pk %}">
                            Remove
                        </a>
                    {% endif %}
                {% endif %}
            </div>

            <div class="col col-lg-2">
                <strong>District</strong>
                <p>{{ post.district }}</p>
                <strong>Area</strong>
                <p>{{ post.area }}</p>
                <strong>House Size</strong>
                <p>{{ post.house_size }}</p>
                <strong>Rent</strong>
                <p>{{ post.rent }} tk</p>
                <a class="btn btn-primary btn-block" href="{% url 'posts:getcontact' pk=post.pk %}">Contact</a>
                <p class="alert alert-primary mt-2">You will be charged 2 tk to reveal contact details</p>
            </div>
        </div>
    </div>
    
{% endblock content %}  

rent/posts/templates/posts/post_form.html
{% extends "base.html" %} 
{% load bootstrap4 %} 
{% load staticfiles %} 
{% block extra_js %}
<script>
    $(document).ready(function () {

        // clear the default data from area_choice, and later update
        // areas based on user's district choice
        $("#area_choice").html('<option value="1" selected>---------</option>');

        $("#district_choice").change(function () {
            console.log("requesting new data");
            var req = $.ajax({
                url: "{% url 'posts:get_location' %}",
                type: "POST",
                data: {
                    user_choice: $("#district_choice option:selected").text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType: "html",

                success: function(data) {
                    console.log("data retrieved");
                    console.log(data);
                    $("#area_choice").html(data);
                },

                error: function() {
                    console.log("error occured");
                }
            });
        });
    });
</script> 
{% endblock extra_js %} 

{% block content %}
<div class="container">
    <h1>Create New Ad</h1>
        {% for message  in messages %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
        <div class="alert alert-primary">
            You will be charged 5 Tk from your phone for posting an Ad
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {% bootstrap_form form %}
            {{ formset.management_form }}
            {% for im_form in formset %}
                {% bootstrap_form im_form %}
            {% endfor %}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

{% endblock content %}